// Generated by CoffeeScript 1.9.2
(function() {
  var Exception;

  module.exports.Exception = Exception = (function() {
    function Exception(message, wrapped) {
      this.message = message;
      this.wrapped = wrapped;
    }

    return Exception;

  })();

}).call(this);

//# sourceMappingURL=exception.js.map
