// Generated by CoffeeScript 1.9.2
(function() {
  var data, setup, should;

  should = require('should');

  setup = require('../../setup');

  data = require('./data');

  describe('Tuple', function() {
    this.beforeEach(function() {
      return setup(this, data);
    });
    return it('should be able to define a tuple', function() {
      var e;
      e = this.tup.exec(this.ctx);
      e["a"].should.equal(1);
      return e["b"].should.equal(2);
    });
  });

}).call(this);

//# sourceMappingURL=test.js.map
